name: edakBuilder

on: push

jobs:
  makeNightly: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/create-release@v1
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly-${{ github.run_id }}
          release_name: nightly
          body: |
            ðŸ¸ðŸŒ™ ~ Edak Engine build based on the latest commit.
            SHA: `${{ github.sha }}`

  edakWin:
    runs-on: windows-latest
    needs: makeNightly
    steps:
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp

      - name: Install Libraries
        run: |
          haxelib install hmm
          haxelib run hmm install

      - name: Create Version Tag and Asset
        run: |
          echo "${{github.run_id}}" > VERSION
          echo "${{github.run_id}}" > assets/data/_aver.txt

      - name: Build Game
        run: haxelib run lime build windows -DACTION
        
      - name: Zip Build
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r edakWin.zip export/release/windows/bin
      
      - name: Publish Build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./edakWin.zip
          asset_name: edakWin.zip
          asset_content_type: application/zip

  edakMac:
    runs-on: macos-11
    needs: makeNightly
    steps:
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null --quiet

      - name: Install Libraries
        run: |
          haxelib install hmm
          haxelib run hmm install

      - name: Create Version Tag and Asset
        run: |
          echo "${{github.run_id}}" > VERSION
          echo "${{github.run_id}}" > assets/data/_aver.txt
      
      - name: Build Game
        run: |
          haxelib run lime build macos -DACTION
          sudo chmod +x "export/release/macos/bin/EdakEngine.app/Contents/MacOS/EdakEngine"

      - name: Zip Build
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r edakMac.zip export/release/macos/bin
      
      - name: Publish Build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./edakMac.zip
          asset_name: edakMac.zip
          asset_content_type: application/zip

# weird vlc/hxcodec issues, rip for now
#  edakLinux:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
      
#      - uses: krdlab/setup-haxe@master
#        with:
#          haxe-version: 4.2.5
        
#      - name: Install Haxelib
#        run: |
#          sudo apt-get install libvlc-dev
#          sudo apt-get install libvlccore-dev
#          haxelib setup ~/haxelib
      
#      - name: Install Libraries
#        run: |
#          haxelib install lime
#          haxelib install openfl
#          haxelib install flixel
#          haxelib install flixel-addons
#          haxelib install flixel-ui
#          haxelib install hxcodec 2.5.1
#          haxelib install yaml
#          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
#          haxelib git sscript https://github.com/AltronMaxX/SScript
      
#      - name: Create Version Tag
#        run: echo "${{github.run_id}}" > VERSION
      
#      - name: Build Game
#        run: haxelib run lime build linux --app-version="1.0.0-${{github.run_id}}"
      
#      - name: Publish Build
#        uses: actions/upload-artifact@v3
#        with:
#          name: edakLinux
#          path: 'export/release/linux/bin'   
